categories:
- Variant Analysis
description: Galaxy Freebayes Bayesian genetic variant detector tool
homepage_url: https://github.com/ekg/freebayes
long_description: |
  This tool is a complete wrapper for FreeBayes software.
name: freebayes
owner: sanbi-uwc
remote_repository_url: https://github.com/SANBI-SA/tools-sanbi-uwc/tree/master/tools/freebayes
type: unrestricted
