categories:
    - Statistics
    - Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version 2.2 of qualimap.
long_description: |
    Qualimap 2 is a platform-independent application written in Java and R that provides both a Graphical User Inteface
    (GUI) and a command-line interface to facilitate the quality control of alignment
    sequencing data and its derivatives like feature counts.
    http://qualimap.bioinfo.cipf.es/
name: package_qualimap_2_2
owner: sanbi-uwc
remote_repository_url: https://github.com/zipho/package_qualimap_2_2
type: tool_dependency_definition
