categories:
- Sequence Analysis
description: Tool designed because ARTIC protocol can generate chimeric reads, this tool is for performing length filtering
long_description: |
  The artic pipeline is designed to help run the artic bioinformatics protocols;
    for example the nCoV-2019 novel coronavirus protocol.
    Features include: read filtering, primer trimming, amplicon coverage normalisation,
    variant calling and consensus building
homepage_url: https://github.com/artic-network/fieldbioinformatics
name: artic_guppyflex
owner: sanbi-uwc
remote_repository_url: https://github.com/zipho/tools-sanbi-uwc/tree/master/tools/artic_guppyflex
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} (ARTIC tool suite)"
suite:
  name: "suite_artic"
  description: A bioinformatics pipeline for working with virus sequencing data sequenced with nanopore
