categories:
- Next Gen Mappers
- Metagenomics
- Variant Analysis
description: Fast and sensitive variant calling from next-gen sequencing data
homepage_url: http://csb5.github.io/lofreq/
long_description: |
  LoFreq* (i.e. LoFreq version 2) is a fast and sensitive variant-caller for inferring SNVs and indels from next-generation sequencing data.
  It makes full use of base-call qualities and other sources of errors inherent in sequencing (e.g. mapping or base/indel alignment uncertainty),
  which are usually ignored by other methods or only used for filtering.
name: lofreq
owner: sanbi-uwc
remote_repository_url: https://github.com/SANBI-SA/tools-sanbi-uwc/tree/master/tools/lofreq
type: unrestricted
